# build settings
markdown: kramdown
remote_theme: pages-themes/time-machine@v0.2.0
plugins:
- jekyll-remote-theme


title: Path To Asha Empire
description: Get ready for the ultimate sci-fi gaming experience as you step into the world of the Asha Empire.
