# build settings
markdown: kramdown
remote_theme: pages-themes/time-machine@v0.2.0
plugins:
- jekyll-remote-theme
google_analytics: G-NHDCW35LLY


title: Path To Asha Empire
description: The Millennial Roadmap is a timeline of events leading up to the year 3039, the setting of science fiction game.
